### ISSUE TITLE
Service Provider listing Enhancements

### ISSUE THREAD

**Issue by umairsy** [erpnext/foundation#120]
- [ ] Remove free/non-member Service Providers. We have taken upvote from the community via forum. Also stop new free listing.

- [ ] Not all Members want Service Provider listing. For the paid members, in the Service Provider page is stopped for website view, still listing is there in the list of Service Provider. Check Konrad's listing for example. 

![screen shot 2018-03-01 at 3 55 58 pm](https://user-images.githubusercontent.com/910238/36839819-1effbdea-1d69-11e8-8073-45f1e5bab61d.png)

**Comment by raghukamath** [comment]
Removed the listing of other providers in this section.
Remaining todo is to disable the name if show on website is not enabled
