### ISSUE TITLE
Clicking on services icon redirect to manufacturing

### ISSUE THREAD

**Issue by PawanMeh** [erpnext/foundation#123]
![website_bug](https://user-images.githubusercontent.com/20460498/36850774-a05ecf42-1d8d-11e8-9a28-ab55c71d33fd.gif)

**Comment by raghukamath** [comment]
@PawanMeh thanks for the report. Can you also tell you browsers name and versions. because the icons should be in grid and not vertical line.

**Comment by PawanMeh** [comment]
@raghukamath this was in an older version of Safari:Version 9.1.1 (11601.6.17) but on the newer versions of chrome and firefox it is fine.

Also, I am seeing bold text a lot in the website, I personally don't prefer it but maybe that is a design decision. This is a sample from the page, https://erpnext.org/about - it shows "None" in bold, I assume bold is intended to present a strong image but "None" seems like a bug

![none_text](https://user-images.githubusercontent.com/20460498/36883514-e2b77c22-1e00-11e8-83a4-fc5c5f9e20d8.png)

**Comment by raghukamath** [comment]
> it shows "None" in bold, I assume bold is intended to present a strong image but "None" seems like a bug

Yes it was a bug, I fixed it now.
