### ISSUE TITLE
Salary slip default month salary

### ISSUE THREAD

**Issue by maheshengg** [erpnext/foundation#132]
New Salary > Select Employee > start and to month should be earlier month and not the current month.

We release salary of February in the first week of March

pls do the changes regarding default month for new salary slip.

Regards,
Mahesh

**Comment by raghukamath** [comment]
I think this bug should be filed in erpnext and not in foundation repo

**Comment by manassolanki** [comment]
I have created the issue in the erpnext repo. This can be closed.

**Comment by raghukamath** [comment]
closing this then

**Comment by maheshengg** [comment]
Opps Sorry. Didnt realize I was on the wrong forum.
