### ISSUE TITLE
clicking on service provider links raises Uncaught Server Exception 

### ISSUE THREAD

**Issue by clarkejj** [erpnext/foundation#138]
This works https://erpnext.org/service-providers/ridhosribumi

But this one and many others do not https://erpnext.org/service-providers/ardan-peddell

Reported here https://discuss.erpnext.com/t/service-providers-at-erpnext-org-doesnt-work/34695

**Comment by raghukamath** [comment]
fixed now

**Comment by clarkejj** [comment]
Thank you Raghavendra
