### ISSUE TITLE
frappe.limits.update_space_usage

### ISSUE THREAD

**Issue by Balmaa** [erpnext/foundation#232]
{'retry': 0, 'log': <function log at 0x7f39c3788320>, 'site': u'erpnext.co.in', 'event': u'hourly', 'method_name': u'frappe.limits.update_space_usage', 'method': <function update_space_usage at 0x7f39c3a4c0c8>, 'user': u'Administrator', 'kwargs': {}, 'async': True, 'job_name': u'frappe.limits.update_space_usage'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/limits.py", line 207, in update_space_usage
    files_size += get_folder_size(frappe.get_site_path("private", "files"))
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'

**Comment by Balmaa** [comment]
Can anyone look on this and explain what is this.

**Comment by kennethsequeira** [comment]
Please report these problems on either

1. Forum: https://discuss.erpnext.com

2. Github repo: https://github.com/frappe/erpnext/issues
