### ISSUE TITLE
foundation/www/assets/img/setup/data-import%20 data-import has a space at the end

### ISSUE THREAD

**Issue by aleksas** [erpnext/foundation#282]
Open https://github.com/erpnext/foundation/blob/master/foundation/www/assets/img/setup/data-import%20

notice %20 at the end

and try
https://github.com/erpnext/foundation/blob/master/foundation/www/assets/img/setup/data-import

to see that it leads to 404

Naming issue resulted in that repo can not be checked out on windows due to bad path.

@kennethsequeira

**Comment by kennethsequeira** [comment]
The space at the end is the culprit. Working on the fix
