### ISSUE TITLE
404 Not Found when clicking 'Find out more ways of deploying ERPNext'

### ISSUE THREAD

**Issue by Segebre** [erpnext/foundation#382]
When I am on the page `https://erpnext.org/docs/user/manual/en/introduction/implementation-strategy`  and I click on `Find out more ways of deploying ERPNext` I get redirected to `https://erpnext.org/docs/user/manual/en/introduction/docs/user/manual/en/introduction/getting-started-with-erpnext` which displays a Not Found message.

I should not be getting to a Not Found message.

**Comment by kennethsequeira** [comment]
Fixed
