### ISSUE TITLE
app-development/how-to-improve-a-standard-control page error

### ISSUE THREAD

**Issue by aleksas** [erpnext/foundation#410]
![image](https://user-images.githubusercontent.com/594470/52793146-b5263e00-3075-11e9-93b9-33af29df068f.png)

**Comment by vrms** [comment]
are you sure this is the right place for this issue?

This repo here is for the website erpnext.org, not ERPNext

**Comment by aleksas** [comment]
You are probably right. Opened [here](https://github.com/frappe/frappe/issues/6940)
