### ISSUE TITLE
https://erpnext.org/chapter-list responds 404 not found 

### ISSUE THREAD

**Issue by clarkejj** [erpnext/foundation#412]
Note also this https://github.com/erpnext/foundation/issues/371

thank you!

**Comment by vrms** [comment]
this one is the workign one: https://erpnext.org/chapters

I agree it would be beneficial to remove the other one (~/chapter-list)

**Comment by kennethsequeira** [comment]
up and running 😅

![image](https://user-images.githubusercontent.com/33246109/54496305-c16f1680-4913-11e9-9686-2f4d127b46ab.png)

**Comment by vrms** [comment]
what is the point in having 2 different listing? https://github.com/erpnext/foundation/issues/371
