### ISSUE TITLE
Foundation fellowship

### ISSUE THREAD

**Issue by netchampfaris** [erpnext/foundation#67]
One person can nominate a contributor, and if 5 members approve he becomes a Foundation fellow.

**Comment by asharamseervi** [comment]
I would like to nominate:

1. https://github.com/revant
2. https://github.com/tundebabzy
3. http://github.com/sbkolate/

**Comment by Tropicalrambler** [comment]
+1 for https://github.com/revant

**Comment by vishdha** [comment]
+1.

**Comment by gaurav-naik** [comment]
+1 for https://github.com/revant

**Comment by FinForceConsulting** [comment]
@asharamseervi: could we please have some more details on why you proposing them?
May be you could think on these points:
1) Introduction of the nominated person
2) What problem did they solved?
3) What contributions did they make?
4) How is their contributions helping EN community

**Comment by PawanMeh** [comment]
+1 for https://github.com/revant

**Comment by sbkolate** [comment]
+1 for:
https://github.com/MaxMorais
https://github.com/revant
HealthCare Developers
Team who made ERPNext document in other language(Français, Português, Español)
Top 3 from Hall of Fame  translation portal. (https://translate.erpnext.com/hall-of-fame)
https://github.com/netchampfaris (for UI fix and UI improvement)

Also sorry if I miss someone from following contributor list.
https://github.com/frappe/frappe/graphs/contributors
https://github.com/frappe/erpnext/graphs/contributors 

Also there should be equal fellowship opportunity for Developers and Other Contributors. (Domain Expert who share their knowledge, document improvement, translation portal member, Discuss forum users, meetup organisers etc)

**Comment by sbkolate** [comment]
Pull request for Fellowship doctype tested and merged https://github.com/erpnext/foundation/pull/90
Voting are in progress for Fellowship, so closing this issue
