### ISSUE TITLE
Login should be easily visible on foundation website

### ISSUE THREAD

**Issue by PawanMeh** [erpnext/foundation#81]
1. If you go to https://erpnext.org, you would not see any link to login. It is suggested to add login as per screen shot shown below

![erpnext_login](https://user-images.githubusercontent.com/20460498/31710647-45bd769e-b413-11e7-8f24-0aab56da53dd.png)

Currently, I think a new user would have to scroll down to find "Member Login", this may not be ideal.

**Comment by sbkolate** [comment]
Also need to change top menu something more meaning full.

Example: 
Docs -> User Manual
Service -> Members
Member ->
     - Foundation Member
     - Chapters
     - Fellow Ship
Jobs -> Hire Developer
Conference
App Store
   -Published APP
   - Frappe
   - ERPNext
   - Unpublished APP [Beta]
  - Fleet Tracking
  - Quickbook Connector
Reviews
About
Contact
  - Support Email
  - Twitter feed
  - Facebook feed
  - Meet up group and forum link

This is just idea. It can  be improved a lot.

**Comment by sbkolate** [comment]
Login is added and Menu is reorganised, so closing this issue
<img width="1064" alt="screen shot 2017-11-10 at 9 47 28 pm" src="https://user-images.githubusercontent.com/6648915/32667476-ca0c9128-c660-11e7-8b56-4ad2f949ff00.png">
