### ISSUE TITLE
Enable bid workflow in jobs

### ISSUE THREAD

**Issue by sbkolate** [erpnext/foundation#82]
Enable job status as Open, working, done
Show completed job on service provider profile with review and job status.

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/86

**Comment by sbkolate** [comment]
+1
Can you write path to fix old job status.
As it is old database, old job status should present in database, from that you can update status completed.
For other job less than 2 month job status as Expired.

Also in old foundation app, bidding workflow is already present.
You can check source code here
https://github.com/frappe/community_erpnext_com/tree/master/community_erpnext_com/erpnext_community_portal/doctype/frappe_job_bid
