### ISSUE TITLE
update conf 2017 page with youtube video link and change disabled button css

### ISSUE THREAD

**Issue by sbkolate** [erpnext/foundation#93]
<img width="1218" alt="screen shot 2017-11-05 at 11 17 30 pm" src="https://user-images.githubusercontent.com/6648915/32417423-9e5209a8-c27f-11e7-8d24-f75b3139f61e.png">

Change disabled button css to more visible
current css
<img width="790" alt="screen shot 2017-11-05 at 11 19 29 pm" src="https://user-images.githubusercontent.com/6648915/32417440-cee98050-c27f-11e7-857c-931a616f711e.png">

new css
<img width="785" alt="screen shot 2017-11-05 at 11 18 35 pm" src="https://user-images.githubusercontent.com/6648915/32417444-e93910f6-c27f-11e7-8d7a-ff5f00f39166.png">

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/94
